"""create initial schema

Revision ID: 4fa136281b74
Revises: 
Create Date: 2026-09-12 20:23:53.586895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4fa136281b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_movie_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_table('theater',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theater_city'), 'theater', ['city'], unique=False)
    op.create_table('auditorium',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('theater_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theater_id', 'name', name='uq_auditorium_theater_name')
    )
    op.create_index(op.f('ix_auditorium_theater_id'), 'auditorium', ['theater_id'], unique=False)
    op.create_table('seat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auditorium_id', sa.Uuid(), nullable=False),
    sa.Column('row_label', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('REGULAR', 'PREMIUM', 'RECLINER', name='seatcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seat_number > 0', name='ck_seat_number_positive'),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditorium.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditorium_id', 'row_label', 'seat_number', name='uq_seat_location')
    )
    op.create_index(op.f('ix_seat_auditorium_id'), 'seat', ['auditorium_id'], unique=False)
    op.create_table('show',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('auditorium_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', name='showstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_show_price_nonnegative'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_show_end_after_start'),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditorium.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_show_auditorium_starts', 'show', ['auditorium_id', 'starts_at'], unique=False)
    op.create_index('ix_show_movie_starts', 'show', ['movie_id', 'starts_at'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_booking_amount_nonnegative'),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_booking_idempotency_key'),
    sa.UniqueConstraint('payment_reference', name='uq_booking_payment_reference')
    )
    op.create_index('ix_booking_show', 'booking', ['show_id'], unique=False)
    op.create_index('ix_booking_status', 'booking', ['status'], unique=False)
    op.create_table('show_seat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='showseatstatus'), nullable=False),
    sa.Column('hold_booking_id', sa.Uuid(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_show_seat_price_nonnegative'),
    sa.ForeignKeyConstraint(['hold_booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'seat_id', name='uq_show_seat')
    )
    op.create_index('ix_show_seat_hold_expires', 'show_seat', ['hold_expires_at'], unique=False)
    op.create_index('ix_show_seat_show_status', 'show_seat', ['show_id', 'status'], unique=False)
    op.create_table('booking_seat',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('show_seat_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seat.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'show_seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_seat')
    op.drop_index('ix_show_seat_show_status', table_name='show_seat')
    op.drop_index('ix_show_seat_hold_expires', table_name='show_seat')
    op.drop_table('show_seat')
    op.drop_index('ix_booking_status', table_name='booking')
    op.drop_index('ix_booking_show', table_name='booking')
    op.drop_table('booking')
    op.drop_index('ix_show_movie_starts', table_name='show')
    op.drop_index('ix_show_auditorium_starts', table_name='show')
    op.drop_table('show')
    op.drop_index(op.f('ix_seat_auditorium_id'), table_name='seat')
    op.drop_table('seat')
    op.drop_index(op.f('ix_auditorium_theater_id'), table_name='auditorium')
    op.drop_table('auditorium')
    op.drop_index(op.f('ix_theater_city'), table_name='theater')
    op.drop_table('theater')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
